stages:
  generate-training-data:
    cmd: python -W ignore -m src.data_creation_racipe --network ${network}
    deps:
    - src/data_creation_racipe.py
    params:
    - network
    outs:
    - data/training/raw
  
  generate-validation-data:
    cmd: python -W ignore -m src.data_creation_racipe --validation --network ${network}
    deps:
    - src/data_creation_racipe.py
    params:
    - data_creation
    outs:
    - data/validation/raw  

  process-validation-data:
    cmd: python -W ignore -m src.data_processing --validation
    deps:
    - src/data_processing.py
    - data/validation/raw
    params:
    - model
    - data_creation
    outs:
    - data/validation/processed

  process-training-data:
    cmd: python -W ignore -m src.data_processing
    deps:
    - src/data_processing.py
    - data/training/raw
    params:
      - model
      - data_creation
    outs:
    - data/training/processed  

  training:
    cmd: python -W ignore -m src.training
    deps:
    - src/training.py
    - data/training/processed
    params:
    - training
    - model
    - model_name
    outs:
    - models/latest.pth

  validation:
      cmd: python -W ignore -m src.validation --network ${network}
      deps:
      - src/validation.py
      - data/validation/processed
      - src/visualization.py
      - models/latest.pth
      params:
      - model
      - model_name

  visualization:
      cmd: python -W ignore -m src.visualization --network ${network}
      deps:
      - src/visualization.py
      - data/validation/processed
      - models/latest.pth
      params:
      - model
      - model_name
      - visualization

  # unsupervised:
  #   cmd: python -W ignore -m src.unsupervised --network ${network}
  #   deps:
  #   - src/validation.py
  #   - src/unsupervised.py
  #   - data/validation/raw/perturbations
