stages:
  generate-training-data:
    cmd: python -W ignore -m src.data_creation --data_split=train --network ${network}
    deps:
    - src/data_creation.py
    params:
    - network
    - data_creation
    outs:
    - data/train/raw
  
  generate-validation-data:
    cmd: python -W ignore -m src.data_creation --data_split=val --network ${network}
    deps:
    - src/data_creation.py
    params:
    - network
    - data_creation
    outs:
    - data/val/raw  

  generate-test-data:
    cmd: python -W ignore -m src.data_creation --data_split test --network ${network}
    deps:
    - src/data_creation.py
    params:
    - network
    - data_creation
    outs:
    - data/test/raw

  process-training-data:
    cmd: python -W ignore -m src.data_processing --data_split train
    deps:
    - src/data_processing.py
    - data/train/raw
    params:
      - model
      - data_creation
    outs:
    - data/train/processed  

  process-validation-data:
    cmd: python -W ignore -m src.data_processing --data_split=val
    deps:
    - src/data_processing.py
    - data/val/raw
    params:
    - model
    - data_creation
    outs:
    - data/val/processed

  process-test-data:
    cmd: python -W ignore -m src.data_processing --data_split test
    deps:
    - src/data_processing.py
    - data/test/raw
    params:
    - model
    - data_creation
    outs:
    - data/test/processed

  training:
    cmd: python -W ignore -m src.training
    deps:
    - src/training.py
    - data/train/processed
    params:
    - training
    - model
    - model_name
    outs:
    - models/latest.pth

  validation:
      cmd: python -W ignore -m src.validation --network ${network}
      deps:
      - src/validation.py
      - data/val/processed
      - src/visualization.py
      - models/latest.pth
      params:
      - model
      - model_name

  visualization:
      cmd: python -W ignore -m src.visualization --network ${network}
      deps:
      - src/visualization.py
      - data/val/processed
      - models/latest.pth
      params:
      - model
      - model_name
      - visualization

  # unsupervised:
  #   cmd: python -W ignore -m src.unsupervised --network ${network}
  #   deps:
  #   - src/validation.py
  #   - src/unsupervised.py
  #   - data/validation/raw/perturbations
