stages:
  generate-training-steady-states:
    cmd: python -W ignore -m src.steady_state_generation --network ${network}
    deps:
    - src/steady_state_generation.py
    params:
    - network
    outs:
    - data/training/raw/steady_states

  generate-validation-steady-states:
    cmd: python -W ignore -m src.steady_state_generation --network ${network} --validation
    deps:
    - src/steady_state_generation.py
    params:
    - network
    outs:
    - data/validation/raw/steady_states

  generate-training-data:
    cmd: python -W ignore -m src.data_creation_grins --network ${network}
    deps:
    - src/data_creation.py
    - data/training/raw/steady_states
    params:
    - network
    outs:
    - data/training/raw/perturbations
  
  generate-validation-data:
    cmd: python -W ignore -m src.data_creation_grins --validation --network ${network}
    deps:
    - src/data_creation.py
    - data/validation/raw/steady_states
    params:
    - data_creation
    outs:
    - data/validation/raw/perturbations    
    
  #   cmd: python -W ignore -m src.data_creation --network ${network}
  #   deps:
  #   - src/data_creation.py
  #   params:
  #   - network
  #   outs:
  #   - data/training/raw
  
  # generate-validation-data:
  #   cmd: python -W ignore -m src.data_creation --validation --network ${network}
  #   deps:
  #   - src/data_creation.py
  #   params:
  #   - data_creation
  #   outs:
  #   - data/validation/raw

  process-validation-data:
    cmd: python -W ignore -m src.data_processing --validation
    deps:
    - src/data_processing.py
    - data/validation/raw/perturbations
    params:
    - model
    - data_creation
    outs:
    - data/validation/processed

  process-training-data:
    cmd: python -W ignore -m src.data_processing
    deps:
    - src/data_processing.py
    - data/training/raw/perturbations
    params:
      - model
      - data_creation
    outs:
    - data/training/processed  

  training:
    cmd: python -W ignore -m src.training
    deps:
    - src/training.py
    - data/training/processed
    params:
    - training
    - model
    - model_name
    outs:
    - models/latest.pth

  validation:
      cmd: python -W ignore -m src.validation --network ${network}
      deps:
      - src/validation.py
      - data/validation/processed
      - src/visualization.py
      - models/latest.pth
      params:
      - model
      - model_name

  visualization:
      cmd: python -W ignore -m src.visualization --network ${network}
      deps:
      - src/visualization.py
      - data/validation/processed
      - models/latest.pth
      params:
      - model
      - model_name
      - visualization

  unsupervised:
    cmd: python -W ignore -m src.unsupervised --network ${network}
    deps:
    - src/validation.py
    - src/unsupervised.py
    - data/validation/raw/perturbations
