data_creation:
    training_size: 1000
    validation_size: 1000
    test_size: 1000
    normalize_data: true
network: tiny
model: pdgrapher
model_name: pdgrapher_control
on_cluster: true
training:
    alpha: 0.5
    batch_size: 64
    class_weighting: false
    epochs: 20  #fix of by one epoch
    graph_weighting: false
    hidden_size: 128
    heads: 4
    layers: 2
    dropout: 0.3
    learning_rate: 1.0e-4
    subsample: false
    weight_decay: 5.0e-4
