data_creation:
    n_samples: 500
    training_share: 0.6
    normalize_data: true
    graph_noise:
        missing_edges: 0.1
        wrong_edges: 0.1
        missing_nodes: 0
        rewired_edges: 0

network: custom_10
on_cluster: false
seed: 42
model: pdgrapher
model_name: pdgrapher_default
training:
    alpha: 0.5
    batch_size: 64
    class_weighting: false
    epochs: 20  #fix of by one epoch
    graph_weighting: false
    hidden_size: 128
    heads: 4
    layers: 2
    dropout: 0.3
    learning_rate: 1.0e-4
    subsample: false
    weight_decay: 5.0e-4
