data_creation:
    n_samples: 1000
    training_share: 0.6
    normalize_data: true
network: tiny
on_cluster: false
seed: 42
model: GAT
model_name: gat_control2
training:
    alpha: 0.5
    batch_size: 64
    class_weighting: false
    epochs: 2  #fix of by one epoch
    graph_weighting: false
    hidden_size: 128
    heads: 4
    layers: 2
    dropout: 0.3
    learning_rate: 1.0e-4
    subsample: false
    weight_decay: 5.0e-4
