[project]
name = "source-detection-in-grns"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12, < 3.13"
dependencies = [
    "dvc>=3.60.1",
    "grins[cuda12]>=0.1.2",
    "numpy>=2.3.1",
    "torch>=2.7.1",
    "torch-geometric>=2.6.1",
]
